### ISSUE TITLE
Extension not showing up in Scratch VM

### ISSUE THREAD

**Issue by babmv-onscratch** [dalelane/scratch-extension-development#11]
I am currently developing a Scratch extension using this repository as a template, and made two test Scratch extensions using your tutorial, one being the 'syllable' extension as shown in the INSTRUCTIONS.md file, and followed all instructions exactly. I also made another extension which following the same steps, except I made a block with a different name, and opCode to test if I could modify all parts of the block correctly for the extension I was making. Although both of the extensions worked perfectly fine at the time, I used the terminal to create new ports to test my extensions, and tested them, only to go into my Scratch VM, and not see either test extensions anywhere on their repositories.

Have any of you encountered the same issue as me? If not, do I need to provide more information on my extensions, or could it possibly be an issue with the Scratch VM or this Github repository itself?

**Comment by dalelane** [comment]
Can you describe what you mean by "I used the terminal to create new ports" please?

**Comment by TheNoceboEffect** [comment]
I used the terminal, and typed in "./0-setup.sh" at first, a few months ago, when I first made my extension, before typing "./2-build.sh" to set up my extension, which worked at the time. Then, I typed in "./2-build.sh" to make another port to test my extension, since I tested the port I made earlier, and the extension wasn't anywhere on the Scratch VM. I tried it on the new port I made, using "./2-build.sh", and the extension didn't show up, even though it worked earlier.

**Comment by dalelane** [comment]
It's a bit difficult to follow what you've done from the description. If you'd like to point me at your repo, I can take a look and see if I can spot the issue

**Comment by TheNoceboEffect** [comment]
I'll publish my repositories now on my profile.

**Comment by TheNoceboEffect** [comment]
The extensions are "syllable" and "my-scratch-extension"

**Comment by dalelane** [comment]
They seem okay to me - I forked your repos and just published them as-is, and although they both appear to be identical, they do both seem to be working. 

https://dalelane.github.io/syllable-testing/scratch/
https://dalelane.github.io/my-scratch-extension-testing/scratch/

Did you perhaps skip a step somewhere?
