### ISSUE TITLE
Issue Importing and Using 'scratch-audio' NPM Package in Scratch Extension

### ISSUE THREAD

**Issue by babmv-onscratch** [dalelane/scratch-extension-development#12]
I followed all of the instructions in the INSTRUCTIONS.md file for installing NPM packages in my Scratch extension, which worked properly in my extension, however I don't know how to import other NPM packages, like 'scratch-audio' in my Scratch Extension. I've seen some sources saying that I should put 'javascript const scratchAudio = require('scratch-audio');', however the 'javascript' part of the script was listed as an error. So should I instead type in 'const scratchAudio' at the beginning of my code, do I put this script somewhere else in my code? Or do I instead type
"constructor (runtime) {
  import('syllable')
    .then((syllableModule) => {
      this.syllable = syllableModule.syllable;
    });
}", which is the code you provided in the INSTRUCTIONS.md file, except replace all instances of 'syllable' with 'scratch-audio', the NPM package I am using in my Scratch extension?

**Comment by dalelane** [comment]
scratch-audio is already part of Scratch so there is no need to separately add another version and instance of it. 

You get access to the Scratch runtime in the constructor for your extension ([here](https://github.com/dalelane/scratch-extension-development/blob/master/your-scratch-extension/index.js#L7)), and `runtime.audioEngine` gives you access to the scratch-audio module, that has already been loaded and configured.

**Comment by TheNoceboEffect** [comment]
Thank you!
