### ISSUE TITLE
how do i change these things?

### ISSUE THREAD

**Issue by bubzilla** [dalelane/scratch-extension-development#4]
how do i change the extension folder name, how it appears in the library, and add more????

**Comment by dalelane** [comment]
The extension name (as presented in the Scratch UI) comes from 

https://github.com/dalelane/scratch-extension-development/blob/master/your-scratch-extension/index.js#L19-L20

**Comment by dalelane** [comment]
The extension name (as presented in the extensions library) comes from 

https://github.com/dalelane/scratch-extension-development/blob/master/patches/scratch-gui.patch#L20 
https://github.com/dalelane/scratch-extension-development/blob/master/patches/scratch-gui.patch#L24

**Comment by bubzilla** [comment]
how could i rename the folder?

**Comment by dalelane** [comment]
if you search for all references of `your-scratch-extension` in the repo, you would need to update all of them
