### ISSUE TITLE
successfully run ./4-publish.sh but got error when try the link

### ISSUE THREAD

**Issue by chingoduc** [dalelane/scratch-extension-development#9]
Hi,

I have tried to run your difffrent blocks of the extension. At the last stage, I have run ./4-publish.sh with success, but when I tried the link : https://username.git.io/extensionname/scratch I got 404 error. Can you help?
Thanks,
Chi Ngo

**Comment by dalelane** [comment]
Please take another look at the instructions in https://github.com/dalelane/scratch-extension-development/blob/master/INSTRUCTIONS.md#publish-your-finished-extension 

In particular, I suspect you may have skipped the bit where you substitute in your username and extension name.

**Comment by chingoduc** [comment]
Hi Dale,

Thanks for your prompt feedback. I found out the reason. There was a
spelling error in my link.
It must be https://chingoduc.github.io/new_extension_UI/scratch instead of
https://chingoduc.github.io/new_extension_ui/scratch.

The link with UI works now.

Thanks a lot,
Chi Ngo
